### ISSUE TITLE
FYI: How to also add an Admin UI

### ISSUE THREAD

**Issue by KeKs0r** [hydra-newmedia/bullish#7]
If someone is interested on how to add the Admin UI to Hapi:

https://gist.github.com/KeKs0r/762a2525f2e5cf327e240f0b7827605c

**Comment by fiws** [comment]
Cool, did you think about publishing it as a module? 

btw hapi 17 is out, the syntax is different, but its awesome. bullish 0.6 (only) supports hapi 17.

**Comment by fiws** [comment]
gonna close this as it is not a real issue.
