### ISSUE TITLE
NPM version problem ?

### ISSUE THREAD

**Issue by umens** [hydra-newmedia/bullish#8]
Hey, is this the latest version of the module on npm ? it's not working for me because of the files downloaded from npm are still under the old plugin structure for hapi 16. I'm using hapi 18 and the code on the repo should work for hapi 18.

any thoughts ?

**Comment by guischdi** [comment]
Hi @umens 

sorry for the short delay over the weekend! Indeed, we missed to publish the new hapi 17 compatible version. Sorry for the circumstances, too!

[bullish](https://www.npmjs.com/package/bullish) is now published as v0.7.0 including the hapi v17 adoption.
